import { NextRequest, NextResponse } from "next/server";
import { createServerClient } from "@/lib/supabase/server";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ reportId: string }> }
) {
  const { reportId } = await params;
  const supabase = await createServerClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Fetch report with profile join to verify ownership
  const { data: report, error } = await supabase
    .from("reports")
    .select("*, profiles!inner(user_id, name)")
    .eq("id", reportId)
    .single();

  if (error || !report) {
    return NextResponse.json({ error: "Report not found" }, { status: 404 });
  }

  // Verify ownership
  const profile = report.profiles as { user_id: string; name: string };
  if (profile.user_id !== user.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  // If PDF already generated by worker, redirect to it
  if (report.pdf_url) {
    return NextResponse.redirect(report.pdf_url);
  }

  // No stored PDF — generate printable HTML from markdown content
  if (!report.content) {
    return NextResponse.json(
      { error: "Report has no content" },
      { status: 400 }
    );
  }

  const profileName = profile.name || "Unknown";
  const reportType = (report.report_type || "report").replace(/_/g, " ");
  const date = new Date(report.created_at ?? Date.now()).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const html = generatePrintableHTML(
    report.content,
    reportType,
    profileName,
    date,
    report.language || "en"
  );

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
    },
  });
}

function markdownToHTML(markdown: string): string {
  return (
    markdown
      // Code blocks (before inline processing)
      .replace(
        /```(\w*)\n([\s\S]*?)```/g,
        '<pre style="background:#1e2d4a;padding:16px;border-radius:8px;overflow-x:auto;"><code>$2</code></pre>'
      )
      // Headings
      .replace(
        /^#### (.+)$/gm,
        '<h4 style="color:#e2e8f0;font-size:1rem;margin:1.2em 0 0.5em;">$1</h4>'
      )
      .replace(
        /^### (.+)$/gm,
        '<h3 style="color:#e2e8f0;font-size:1.1rem;margin:1.5em 0 0.5em;">$1</h3>'
      )
      .replace(
        /^## (.+)$/gm,
        '<h2 style="color:#7c3aed;font-size:1.3rem;margin:2em 0 0.8em;border-bottom:1px solid #1e2d4a;padding-bottom:6px;">$1</h2>'
      )
      .replace(
        /^# (.+)$/gm,
        '<h1 style="color:#c9a227;font-size:1.6rem;margin:1.5em 0 0.8em;">$1</h1>'
      )
      // Bold and italic
      .replace(
        /\*\*\*(.+?)\*\*\*/g,
        '<strong><em style="color:#c9a227;">$1</em></strong>'
      )
      .replace(/\*\*(.+?)\*\*/g, '<strong style="color:#c9a227;">$1</strong>')
      .replace(/\*(.+?)\*/g, "<em>$1</em>")
      // Lists
      .replace(
        /^- (.+)$/gm,
        '<li style="margin:4px 0;padding-left:4px;">$1</li>'
      )
      .replace(
        /^(\d+)\. (.+)$/gm,
        '<li style="margin:4px 0;padding-left:4px;">$2</li>'
      )
      // Wrap consecutive <li> in <ul>
      .replace(
        /(<li[^>]*>.*<\/li>\n?)+/g,
        '<ul style="padding-left:20px;margin:8px 0;">$&</ul>'
      )
      // Blockquotes
      .replace(
        /^> (.+)$/gm,
        '<blockquote style="border-left:3px solid #7c3aed;padding-left:12px;color:#94a3b8;margin:12px 0;">$1</blockquote>'
      )
      // Horizontal rule
      .replace(
        /^---$/gm,
        '<hr style="border:none;border-top:1px solid #1e2d4a;margin:24px 0;">'
      )
      // Paragraphs — double newline
      .replace(/\n\n/g, "</p><p>")
      // Single newline to <br>
      .replace(/\n/g, "<br>")
  );
}

function generatePrintableHTML(
  markdown: string,
  reportType: string,
  profileName: string,
  date: string,
  language: string
): string {
  const htmlContent = markdownToHTML(markdown);

  return `<!DOCTYPE html>
<html lang="${language}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${reportType.toUpperCase()} — ${profileName} | JyotishAI</title>
<style>
  * { box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    max-width: 900px;
    margin: 0 auto;
    padding: 40px 24px;
    background: #0a0a1a;
    color: #e2e8f0;
    line-height: 1.8;
  }
  .header {
    text-align: center;
    padding-bottom: 24px;
    border-bottom: 2px solid #c9a227;
    margin-bottom: 32px;
  }
  .header h1 {
    color: #c9a227;
    font-size: 2rem;
    margin: 0 0 8px;
    text-transform: uppercase;
    letter-spacing: 2px;
  }
  .header .meta {
    color: #64748b;
    font-size: 0.9rem;
  }
  .content p { margin: 0 0 16px; }
  .footer {
    margin-top: 48px;
    padding-top: 24px;
    border-top: 1px solid #1e2d4a;
    text-align: center;
    color: #64748b;
    font-size: 0.8rem;
  }
  @media print {
    body { background: white; color: #1a1a2e; padding: 20px; }
    .header h1 { color: #7c3aed; }
    strong { color: #7c3aed !important; }
    h2 { color: #1a1a2e !important; border-color: #ddd !important; }
    .no-print { display: none; }
  }
  .print-btn {
    position: fixed;
    top: 16px;
    right: 16px;
    padding: 10px 20px;
    background: #7c3aed;
    color: white;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    font-size: 0.9rem;
    z-index: 100;
  }
  .print-btn:hover { background: #6d28d9; }
</style>
</head>
<body>
<button class="print-btn no-print" onclick="window.print()">Print / Save PDF</button>
<div class="header">
  <h1>${reportType}</h1>
  <div class="meta">${profileName} &bull; ${date} &bull; Generated by JyotishAI</div>
</div>
<div class="content">
  <p>${htmlContent}</p>
</div>
<div class="footer">
  Generated by JyotishAI — AI-Powered Vedic Astrology
</div>
</body>
</html>`;
}
